"""Added a table to keep track of category types

Revision ID: 04c7d56473fc
Revises: e42c99f22927
Create Date: 2025-04-01 17:12:12.409471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c7d56473fc'
down_revision: Union[str, None] = 'e42c99f22927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses_categories',
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('category_type', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_expenses_categories_category_id'), 'expenses_categories', ['category_id'], unique=False)
    op.add_column('expenses', sa.Column('expense_category_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'expenses', 'expenses_categories', ['expense_category_id'], ['category_id'])
    op.drop_column('expenses', 'expense_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('expense_category', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'expense_category_id')
    op.drop_index(op.f('ix_expenses_categories_category_id'), table_name='expenses_categories')
    op.drop_table('expenses_categories')
    # ### end Alembic commands ###
