"""Created ExpensesLogs model to keep track of expenses added and removed

Revision ID: 283fb60aaea6
Revises: bfde973ccd10
Create Date: 2025-12-27 13:43:56.858861

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "283fb60aaea6"
down_revision: Union[str, None] = "bfde973ccd10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expenses_logs",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("expense_type", sa.TEXT(), nullable=False),
        sa.Column("expense_amount", sa.NUMERIC(), nullable=False),
        sa.Column("expense_category", sa.TEXT(), nullable=False),
        sa.Column("date_of_entry", sa.DATE(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_expenses_logs_id"), "expenses_logs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expenses_logs_id"), table_name="expenses_logs")
    op.drop_table("expenses_logs")
    # ### end Alembic commands ###
