"""Models to input expenses and keep track of categories

Revision ID: bfde973ccd10
Revises:
Create Date: 2025-12-26 15:03:25.215772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bfde973ccd10"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expenses_categories",
        sa.Column("category_id", sa.INTEGER(), nullable=False),
        sa.Column("category_type", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("category_id"),
    )
    op.create_index(
        op.f("ix_expenses_categories_category_id"),
        "expenses_categories",
        ["category_id"],
        unique=False,
    )
    op.create_table(
        "expenses",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("expense_category_id", sa.INTEGER(), nullable=False),
        sa.Column("expense_month", sa.NUMERIC(), nullable=False),
        sa.Column("expense_year", sa.NUMERIC(), nullable=False),
        sa.Column("expense_cost", sa.NUMERIC(), nullable=False),
        sa.ForeignKeyConstraint(
            ["expense_category_id"],
            ["expenses_categories.category_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_expenses_id"), "expenses", ["id"], unique=False)

    op.execute(
        """
        INSERT INTO expenses_categories (category_type) VALUES
        ('Rent'),
        ('Bills'),
        ('Transportation'),
        ('Subscriptions'),
        ('Groceries'),
        ('Shopping'),
        ('Eating out'),
        ('Leisure'),
        ('Drinks'),
        ('Holidays'),
        ('Other')
    """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expenses_id"), table_name="expenses")
    op.drop_table("expenses")
    op.drop_index(
        op.f("ix_expenses_categories_category_id"), table_name="expenses_categories"
    )
    op.drop_table("expenses_categories")
    # ### end Alembic commands ###
