"""Create a table to list different categories of expenses

Revision ID: da0ff0c56c80
Revises: e42c99f22927
Create Date: 2025-04-02 10:31:50.615676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da0ff0c56c80"
down_revision: Union[str, None] = "e42c99f22927"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expenses_categories",
        sa.Column("category_id", sa.INTEGER(), nullable=False),
        sa.Column("category_type", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("category_id"),
    )
    op.create_index(
        op.f("ix_expenses_categories_category_id"),
        "expenses_categories",
        ["category_id"],
        unique=False,
    )
    op.add_column(
        "expenses", sa.Column("expense_category_id", sa.INTEGER(), nullable=False)
    )
    op.create_foreign_key(
        None,
        "expenses",
        "expenses_categories",
        ["expense_category_id"],
        ["category_id"],
    )

    op.execute(
        """
        INSERT INTO expenses_categories (category_type) VALUES
        ('Rent'),
        ('Bills'),
        ('Transportation'),
        ('Subscriptions'),
        ('Groceries'),
        ('Shopping'),
        ('Eating out'),
        ('Leisure'),
        ('Drinks'),
        ('Holidays'),
        ('Other')
    """
    )

    op.drop_column("expenses", "expense_category")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "expenses",
        sa.Column("expense_category", sa.TEXT(), autoincrement=False, nullable=False),
    )

    op.drop_constraint(
        "expenses_expense_category_id_fkey", "expenses", type_="foreignkey"
    )

    op.drop_column("expenses", "expense_category_id")
    op.drop_index(
        op.f("ix_expenses_categories_category_id"), table_name="expenses_categories"
    )
    op.drop_table("expenses_categories")
    # ### end Alembic commands ###
