"""Table to keep track of user's expenses

Revision ID: e42c99f22927
Revises:
Create Date: 2025-04-01 16:35:35.351669

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e42c99f22927"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expenses",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("expense_category", sa.TEXT(), nullable=False),
        sa.Column("expense_month", sa.TEXT(), nullable=False),
        sa.Column("expense_year", sa.NUMERIC(), nullable=False),
        sa.Column("expense_cost", sa.NUMERIC(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_expenses_id"), "expenses", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expenses_id"), table_name="expenses")
    op.drop_table("expenses")
    # ### end Alembic commands ###
